# Home Assistant Configuration for Hoymiles MQTT Health Monitoring
# Compatible with Home Assistant 2024.x (Latest Standards)
# Add this to your configuration.yaml or create a separate package

# RESTful sensors to fetch health data (Modern syntax)
rest:
  - resource: "http://192.168.1.31:8090/health"
    scan_interval: 60  # Check every 60 seconds
    sensor:
      - name: "Hoymiles MQTT Health Status"
        unique_id: hoymiles_smiles_health_status
        value_template: "{{ value_json.healthy }}"
        json_attributes:
          - uptime_seconds
          - start_time
          - dtus
          - mqtt
        availability: "{{ value_json is defined }}"
      
      - name: "Hoymiles MQTT Uptime"
        unique_id: hoymiles_smiles_uptime
        value_template: "{{ value_json.uptime_seconds }}"
        unit_of_measurement: "s"
        device_class: duration
        state_class: total_increasing
        availability: "{{ value_json.uptime_seconds is defined }}"
      
      - name: "Hoymiles MQTT Messages Published"
        unique_id: hoymiles_smiles_messages_published
        value_template: "{{ value_json.mqtt.messages_published }}"
        state_class: total_increasing
        availability: "{{ value_json.mqtt.messages_published is defined }}"
      
      - name: "Hoymiles MQTT Errors"
        unique_id: hoymiles_smiles_errors
        value_template: "{{ value_json.mqtt.errors }}"
        state_class: total_increasing
        availability: "{{ value_json.mqtt.errors is defined }}"

  - resource: "http://192.168.1.31:8090/stats"
    scan_interval: 300  # Check every 5 minutes
    sensor:
      - name: "Hoymiles MQTT Database Size"
        unique_id: hoymiles_smiles_db_size
        value_template: "{{ (value_json.database_size_bytes / 1024 / 1024) | round(2) }}"
        unit_of_measurement: "MB"
        state_class: measurement
        suggested_display_precision: 2
        availability: "{{ value_json.database_size_bytes is defined }}"
      
      - name: "Hoymiles MQTT Cached Records"
        unique_id: hoymiles_smiles_cached_records
        value_template: "{{ value_json.total_records }}"
        state_class: measurement
        availability: "{{ value_json.total_records is defined }}"

# Template sensors (Modern HA 2024.x syntax)
template:
  # Binary sensor for overall health
  - binary_sensor:
      - name: "Hoymiles MQTT Healthy"
        unique_id: hoymiles_smiles_healthy
        device_class: connectivity
        state: >-
          {{ states('sensor.hoymiles_smiles_health_status') == 'True' }}
        availability: >-
          {{ states('sensor.hoymiles_smiles_health_status') not in ['unknown', 'unavailable', 'none'] }}
        icon: >-
          {% if states('sensor.hoymiles_smiles_health_status') == 'True' %}
            mdi:check-circle
          {% else %}
            mdi:alert-circle
          {% endif %}
  
  # Detailed DTU monitoring sensors
  - sensor:
      - name: "Hoymiles DTU Last Query"
        unique_id: hoymiles_dtu_last_query
        state: >-
          {% set dtus = state_attr('sensor.hoymiles_smiles_health_status', 'dtus') %}
          {% if dtus and dtus.DTU %}
            {{ dtus.DTU.seconds_since_last_success | default(0) }}
          {% else %}
            unknown
          {% endif %}
        unit_of_measurement: "s"
        device_class: duration
        icon: mdi:clock-outline
        availability: >-
          {{ state_attr('sensor.hoymiles_smiles_health_status', 'dtus') is not none }}
      
      - name: "Hoymiles DTU Query Count"
        unique_id: hoymiles_dtu_query_count
        state: >-
          {% set dtus = state_attr('sensor.hoymiles_smiles_health_status', 'dtus') %}
          {% if dtus and dtus.DTU %}
            {{ dtus.DTU.query_count | default(0) }}
          {% else %}
            0
          {% endif %}
        state_class: total_increasing
        icon: mdi:counter
        availability: >-
          {{ state_attr('sensor.hoymiles_smiles_health_status', 'dtus') is not none }}
      
      - name: "Hoymiles DTU Error Count"
        unique_id: hoymiles_dtu_error_count
        state: >-
          {% set dtus = state_attr('sensor.hoymiles_smiles_health_status', 'dtus') %}
          {% if dtus and dtus.DTU %}
            {{ dtus.DTU.error_count | default(0) }}
          {% else %}
            0
          {% endif %}
        state_class: total_increasing
        icon: mdi:alert-circle-outline
        availability: >-
          {{ state_attr('sensor.hoymiles_smiles_health_status', 'dtus') is not none }}
      
      - name: "Hoymiles DTU Status"
        unique_id: hoymiles_dtu_status
        state: >-
          {% set dtus = state_attr('sensor.hoymiles_smiles_health_status', 'dtus') %}
          {% if dtus and dtus.DTU %}
            {{ dtus.DTU.status | default('unknown') }}
          {% else %}
            unknown
          {% endif %}
        icon: mdi:solar-power
        availability: >-
          {{ state_attr('sensor.hoymiles_smiles_health_status', 'dtus') is not none }}
      
      - name: "Hoymiles MQTT Uptime Formatted"
        unique_id: hoymiles_smiles_uptime_formatted
        state: >-
          {% set uptime = states('sensor.hoymiles_smiles_uptime') | int(0) %}
          {% if uptime > 0 %}
            {% set days = (uptime / 86400) | int %}
            {% set hours = ((uptime % 86400) / 3600) | int %}
            {% set minutes = ((uptime % 3600) / 60) | int %}
            {% if days > 0 %}
              {{ days }}d {{ hours }}h {{ minutes }}m
            {% elif hours > 0 %}
              {{ hours }}h {{ minutes }}m
            {% else %}
              {{ minutes }}m
            {% endif %}
          {% else %}
            unknown
          {% endif %}
        icon: mdi:clock-check-outline
        availability: >-
          {{ states('sensor.hoymiles_smiles_uptime') not in ['unknown', 'unavailable', 'none'] }}

# Automations (Modern HA 2024.x syntax)
automation:
  # Alert when Hoymiles MQTT goes unhealthy
  - id: hoymiles_smiles_unhealthy_alert
    alias: "Hoymiles MQTT - Unhealthy Alert"
    description: "Alert when Hoymiles MQTT application becomes unhealthy"
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.hoymiles_smiles_healthy
        to: "off"
        for:
          minutes: 2
    condition: []
    action:
      - action: persistent_notification.create
        data:
          title: "⚠️ Hoymiles MQTT Unhealthy"
          message: >-
            Hoymiles MQTT application is unhealthy.
            Last DTU query: {{ states('sensor.hoymiles_dtu_last_query') }}s ago
            Error count: {{ states('sensor.hoymiles_dtu_error_count') }}
      # Add your notification service here (uncomment and customize)
      # - action: notify.mobile_app_your_phone
      #   data:
      #     title: "Hoymiles MQTT Unhealthy"
      #     message: "Check your solar monitoring system"
      #     data:
      #       importance: high
      #       ttl: 0
      #       priority: high

  # Alert on high error rate
  - id: hoymiles_smiles_high_errors
    alias: "Hoymiles MQTT - High Error Rate"
    description: "Alert when error count increases significantly"
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.hoymiles_dtu_error_count
    condition:
      - condition: template
        value_template: >-
          {{ trigger.to_state.state | int(0) - trigger.from_state.state | int(0) >= 5 }}
    action:
      - action: persistent_notification.create
        data:
          title: "⚠️ Hoymiles MQTT Errors"
          message: >-
            Multiple errors detected in Hoymiles MQTT.
            Total errors: {{ states('sensor.hoymiles_dtu_error_count') }}
            Increase: {{ trigger.to_state.state | int(0) - trigger.from_state.state | int(0) }}

  # Notify when application restarts
  - id: hoymiles_smiles_restart_notify
    alias: "Hoymiles MQTT - Restart Notification"
    description: "Notify when application restarts"
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.hoymiles_smiles_uptime
    condition:
      - condition: template
        value_template: >-
          {{ trigger.to_state.state | int(0) < trigger.from_state.state | int(0) 
             and trigger.from_state.state not in ['unknown', 'unavailable', 'none'] }}
    action:
      - action: persistent_notification.create
        data:
          title: "ℹ️ Hoymiles MQTT Restarted"
          message: >-
            Hoymiles MQTT application has restarted.
            Previous uptime: {{ trigger.from_state.state }}s
            New start time: {{ state_attr('sensor.hoymiles_smiles_health_status', 'start_time') }}
